// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/profile-ui/ProfileDropdown.tsx": () => import("../components/mockups/profile-ui/ProfileDropdown.tsx"),
  "./components/mockups/profile-ui/ProfileManageDialog.tsx": () => import("../components/mockups/profile-ui/ProfileManageDialog.tsx"),
  "./components/mockups/profile-ui/ProfilePanel.tsx": () => import("../components/mockups/profile-ui/ProfilePanel.tsx")
};
