# launcher name & url
launcher_name=ZalithLauncher 2 Plus
launcher_app_name=Zalith Launcher 2 Plus
launcher_short_name=ZL2+
url_home=https://github.com/Star1xr/ZL2Fix

# your OAuth client id
# Using the public Xbox device-code client ID compatible with login.live.com refresh flow
oauth_client_id=3936adb1-e7bb-4d7b-9951-112adae5341c

# your CurseForge API key
curseforge_api_key=$2a$10$lqBDWbAkrtDAO0lKYbew/.DDkGRT.fZMLfQJdGirpE9VloxF0T5ui

# default key, please add it yourself.
default_store_password=vh#nn%N(#eNjwfA78-77s6&f-cdd(@-7eana-e%!nhj%))!@c
default_key_password=sfv72ghSSNQaadf99-Q69!2

# launcher version
launcher_version_code=200036
launcher_version_name=2.5
