name: Build CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.gitignore'
      - '**/README.md'
      - '**/README_*.md'
      - '**/CHANGELOG.md'
      - '**/CHANGELOG_*.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      variant: Release
    secrets: inherit
